"""
AuditLog dataclass — records every AI decision and human override for compliance.

Every significant event in the system produces an AuditLog record:
  - AI_RECOMMENDATION       → vendor scoring pipeline completed successfully
  - FALLBACK_RECOMMENDATION → Gemini was unavailable; rule-based scorer used
  - ADMIN_OVERRIDE          → Admin manually selected a different vendor
  - AI_RECOMMENDATION_ACCEPTED → Admin accepted the AI recommendation
  - DLQ_FAILURE             → SQS message could not be processed after 3 retries

Records are written to TWO destinations by services/audit_logger.py:
  1. DynamoDB ai-vrs-audit-log  — PII-masked copy (piiMasked=True)
  2. S3 ai-vrs-logs bucket      — unmasked copy with SSE-S3 encryption

Requirements: 6.1, 6.2, 6.3, 6.6
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

# ── Allowed action types ───────────────────────────────────────────────────────
# Each action type maps to a specific event in the system lifecycle.
# Used for filtering in GET /audit-logs and the AuditFilterBar UI component.
VALID_ACTION_VALUES = {
    "AI_RECOMMENDATION",          # Normal path: Gemini generated rationale
    "ADMIN_OVERRIDE",             # Admin replaced AI recommendation with manual choice
    "FALLBACK_RECOMMENDATION",    # Gemini unavailable; rule-based scorer used
    "AI_RECOMMENDATION_ACCEPTED", # Admin accepted the AI recommendation without change
    "DLQ_FAILURE",                # SQS message failed processing and went to DLQ
}


@dataclass
class AuditLog:
    """
    Records every AI decision and human override for compliance and audit purposes.

    Instances are created exclusively by services/audit_logger.py — never
    constructed directly by handler code. The audit_logger ensures:
    - logId is always a UUID v4 (uuid.uuid4())
    - piiMasked is always True for DynamoDB records
    - PII is redacted via pii_masker.mask() before DynamoDB write
    - Unmasked data is written to S3 with SSE-S3 encryption
    """

    # Unique identifier for this audit record (UUID v4 generated by audit_logger)
    logId: str

    # UUID v4 — links this record to the originating job
    jobId: str

    # UUID v4 — the vendor involved (top-ranked for recommendations, selected for overrides)
    # Empty string for DLQ_FAILURE records where no vendor was involved
    vendorId: str

    # Type of event — must be one of VALID_ACTION_VALUES
    action: str

    # Input context at the time of the event (PII-masked for DynamoDB)
    # For AI_RECOMMENDATION: contains job details and ScoreFactors for all ranked vendors
    # For ADMIN_OVERRIDE: contains the original recommendation list
    # For DLQ_FAILURE: contains the failed job ID and failure timestamp
    input: dict

    # Output produced by the event (PII-masked for DynamoDB)
    # For AI_RECOMMENDATION: contains ranked vendor list with rationale and confidence
    # For ADMIN_OVERRIDE: contains the selected vendor ID and override reason
    output: dict

    # Human-readable reason provided by the Admin when overriding a recommendation
    # Only populated for ADMIN_OVERRIDE records; None for all other action types
    overrideReason: Optional[str]

    # Semantic version of the scoring model that produced this record
    # Allows tracing decisions back to a specific model configuration
    modelVersion: str

    # Always True for DynamoDB records — PII has been redacted by pii_masker.mask()
    # The unmasked version is stored in S3 (accessible only to authorised IAM roles)
    piiMasked: bool

    # ISO 8601 UTC timestamp when this audit record was created
    timestamp: str

    # True for FALLBACK_RECOMMENDATION records (Gemini was unavailable)
    # None for all other action types
    aiUnavailable: Optional[bool]

    def __post_init__(self) -> None:
        """Validate the action field immediately after dataclass construction."""
        # Reject unknown action types to prevent silent data quality issues
        if self.action not in VALID_ACTION_VALUES:
            raise ValueError(
                f"Invalid action '{self.action}'. "
                f"Must be one of: {sorted(VALID_ACTION_VALUES)}"
            )
