"""
ScoreFactors and Recommendation dataclasses for the AI Vendor Recommendation System.

ScoreFactors holds the per-vendor breakdown of all 8 scoring dimensions plus
the computed totalScore. It is produced by handlers/vendor_scoring.normalize()
and flows through the entire pipeline:
  vendor_scoring → recommendation → audit_logger → DynamoDB

Recommendation wraps a ScoreFactors with the AI/fallback rationale text,
confidence level, and metadata. It is written to the DynamoDB
ai-vrs-recommendations table and returned by GET /recommendations/{jobId}.

Requirements: 1.2, 1.4, 2.4, 14.2
"""

from dataclasses import dataclass


@dataclass
class ScoreFactors:
    """
    Per-vendor breakdown of all 8 scoring dimensions plus the weighted total.

    All score fields are normalised to [0.0, 1.0] before being combined.
    The totalScore is computed as a weighted sum — see WEIGHTS in
    handlers/vendor_scoring.py for the exact weights.

    This record is attached to every Recommendation and AuditLog so that
    every decision can be fully traced back to its inputs.
    """

    # ── Identity fields ────────────────────────────────────────────────────────
    # Links this score record back to the vendor and job that produced it
    vendorId: str   # UUID v4 — references VendorProfile
    jobId: str      # UUID v4 — references JobEvent

    # ── Dimension scores (all normalised to [0.0, 1.0]) ───────────────────────

    # Completion rate score — used directly from VendorProfile.completionRate
    # Weight: 25% (highest weight — most important signal)
    completionScore: float

    # Availability score — enum mapped: available=1.0, busy=0.5, unavailable=0.0
    # Weight: 20% — vendors with availabilityScore=0.0 are excluded from ranking
    availabilityScore: float

    # Rework rate score — inverted: 1.0 - reworkRate (lower rework = higher score)
    # Weight: 15%
    reworkScore: float

    # Location proximity score — 1.0 exact match, 0.5 same region, 0.0 other
    # Weight: 15%
    locationScore: float

    # Specialization match — binary: 1.0 if job.type in specializations, else 0.0
    # Weight: 10%
    specializationScore: float

    # Response time score — max(0.0, 1.0 - avgResponseTime/24.0), capped at 24h
    # Weight: 8%
    responseTimeScore: float

    # SLA breach score — max(0.0, 1.0 - slaBreachCount/10.0), capped at 10
    # Weight: 4%
    slaBreachScore: float

    # Active jobs score — max(0.0, 1.0 - activeJobs/20.0), capped at 20
    # Weight: 3% — also used as tie-breaker in ranking
    activeJobsScore: float

    # ── Computed fields ────────────────────────────────────────────────────────

    # Weighted sum of all 8 dimension scores, rounded to 6 decimal places
    # Formula: 0.25*completion + 0.20*availability + 0.15*rework + 0.15*location
    #        + 0.10*specialization + 0.08*responseTime + 0.04*slaBreach + 0.03*activeJobs
    totalScore: float

    # Confidence level assigned after ranking: "High", "Medium", or "Low"
    # Determined by score distribution logic in compute_confidence()
    # Set to "" during normalize(), populated after rank_vendors() is called
    confidence: str

    # Semantic version of the scoring model that produced this record
    # Read from S3 model-version.txt via utils/model_version.get_model_version()
    # Included in every record for full traceability (Requirement 14.2)
    modelVersion: str

    # True if the rationale text was generated by Gemini AI
    # False if the fallback rule-based scorer was used
    # Set to False in normalize(); updated by recommendation.py
    isAIGenerated: bool


@dataclass
class Recommendation:
    """
    A ranked vendor suggestion produced by the Scoring_Engine for a specific job.

    Assembled by handlers/recommendation.py after:
    1. vendor_scoring.py computes and ranks ScoreFactors
    2. ai_client.py (or fallback_scorer.py) generates the rationale text

    Written to DynamoDB ai-vrs-recommendations table.
    Returned by GET /recommendations/{jobId} with isFallback flag.
    """

    # UUID v4 — links this recommendation back to the originating job
    jobId: str

    # Rank position in the ordered list (1 = best match, up to 5)
    rank: int

    # UUID v4 — the vendor being recommended
    vendorId: str

    # The vendor's weighted composite score (copy from ScoreFactors.totalScore)
    totalScore: float

    # Full score breakdown — embedded for complete traceability
    # Displayed as the 8-dimension breakdown in the VendorCard UI component
    scoreFactors: ScoreFactors

    # Human-readable explanation of why this vendor was ranked at this position
    # Either AI-generated (Gemini 2.5 Flash) or rule-based (fallback_scorer)
    # Displayed in the RationaleBox UI component
    rationale: str

    # Confidence level: "High", "Medium", or "Low"
    # Displayed as a color-coded ConfidenceBadge in the UI
    # Low confidence triggers an advisory message recommending manual review
    confidence: str

    # Semantic version of the scoring model (copied from ScoreFactors.modelVersion)
    modelVersion: str

    # ISO 8601 UTC timestamp when this recommendation was generated
    timestamp: str

    # True if rationale was generated by Gemini AI, False if rule-based fallback
    # Used to set the isFallback flag on the GET /recommendations response
    isAIGenerated: bool
